export const GET_ALL_SERVICES = "GET_ALL_SERVICES"
export const CREATE_SERVICES = "CREATE_SERVICES"
export const UPDATE_SERVICES = "UPDATE_SERVICES"
export const DELETE_SERVICES = "DELETE_SERVICES"

export const GET_ALL_GALARIES = "GET_ALL_GALARIES"
export const CREATE_GALARIES = "CREATE_GALARIES"
export const UPDATE_GALARIES = "UPDATE_GALARIES"
export const DELETE_GALARIES = "DELETE_GALARIES"



export const GET_ERROR = "GET_ERROR"